apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: jiwon-tech
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "your-access-key-id"
  AWS_SECRET_ACCESS_KEY: "your-secret-access-key"
  AWS_REGION: "us-east-1"

